set names 'utf8';
delete from bjgl_menu;
alter table bjgl_menu auto_increment=1;
insert into bjgl_menu (name, url, order_view, valid, memo) values ('系统管理', '', '0', 1, '');
commit;
delete from bjgl_permission;
alter table bjgl_permission auto_increment=1;
insert into bjgl_permission (name, url, menu_id, order_view, action_name, param_name, param_value, valid, memo, menu_item) values ('用户管理', '/user/user.do', 1, '0', 'user', '', '', 1, '', 1);
insert into bjgl_permission (name, url, menu_id, order_view, action_name, param_name, param_value, valid, memo, menu_item) values ('角色管理', '/user/role.do', 1, '0', 'role', '', '', 1, '', 1);
insert into bjgl_permission (name, url, menu_id, order_view, action_name, param_name, param_value, valid, memo, menu_item) values ('菜单管理', '/user/menu.do', 1, '0', 'menu', '', '', 1, '', 1);
insert into bjgl_permission (name, url, menu_id, order_view, action_name, param_name, param_value, valid, memo, menu_item) values ('权限管理', '/user/permission.do', 1, '0', 'permission', '', '', 1, '', 0);
insert into bjgl_permission (name, url, menu_id, order_view, action_name, param_name, param_value, valid, memo, menu_item) values ('子权限管理', '/user/permissionItem.do', 1, '0', 'permissionItem', '', '', 1, '', 0);
insert into bjgl_permission (name, url, menu_id, order_view, action_name, param_name, param_value, valid, memo, menu_item) values ('日志管理', '/log/log.do', 1, '0', 'log', '', '', 1, '', 1);
commit;
delete from bjgl_permission_item;
alter table bjgl_permission_item auto_increment=1;
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('添加修改', 1, '0', 'manage', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('输入', 1, '0', 'input', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('查看', 1, '0', 'view', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('删除', 1, '0', 'del', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('验证用户名', 1, '0', 'check', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('查询', 1, '0', 'query', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('添加修改', 2, '0', 'manage', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('输入', 2, '0', 'input', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('查看', 2, '0', 'view', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('删除', 2, '0', 'del', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('权限列表', 2, '0', 'findPermissions', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('复制', 2, '0', 'copy', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('添加修改', 3, '0', 'manage', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('输入', 3, '0', 'input', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('查看', 3, '0', 'view', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('删除', 3, '0', 'del', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('添加修改', 4, '0', 'manage', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('输入', 4, '0', 'input', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('查看', 4, '0', 'view', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('删除', 4, '0', 'del', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('添加修改', 5, '0', 'manage', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('输入', 5, '0', 'input', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('查看', 5, '0', 'view', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('删除', 5, '0', 'del', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('查看', 6, '0', 'view', 1, '');
insert into bjgl_permission_item (name, permission_id, order_view, method_name, valid, memo) values ('查询', 6, '0', 'query', 1, '');
commit;
delete from bjgl_role;
alter table bjgl_role auto_increment=1;
insert into bjgl_role (name, valid, memo) values ('系统管理员', 1, '');
commit;
delete from bjgl_user;
alter table bjgl_user auto_increment=1;
insert into bjgl_user (username, password, name, create_time, update_time, login_time, last_login_time, valid, memo) values ('admin', '0192023a7bbd73250516f069df18b500', '管理员', now(), now(), null, null, 1, '');
commit;
delete from bjgl_user_role;
alter table bjgl_user_role auto_increment=1;
insert into bjgl_user_role (user_id, role_id) values (1, 1);
commit;
delete from bjgl_role_permission;
INSERT INTO `bjgl_role_permission` VALUES (1,1,1,'1,2,3,4,5,6'),(2,1,2,'7,8,9,10,11,12'),(3,1,3,'13,14,15,16'),(4,1,4,'17,18,19,20'),(5,1,5,'21,22,23,24'),(6,1,6,'25,26');
commit;
